source 'https://rubygems.org'

gem 'rails', '3.2.8'
gem 'mysql2'
gem 'jquery-rails'
gem 'haml'
gem 'to_xls'
gem 'spreadsheet'
gem 'thin'
gem 'net-scp'
gem 'rmagick'
gem 'parallel'
gem 'debugger'

group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'therubyracer', :platforms => :ruby
  gem 'uglifier', '>= 1.0.3'
end

