	insert into `magento`.`m_products` (select `m_mbk_product_code`,
	"",
	"Default",
	"simple",
	`m_category_ids`,
	"base",
  REPLACE(`m_name`,'"',''), 
  CASE WHEN LENGTH(`m_description`) = 0 THEN "NONE" ELSE REPLACE(`m_description`,'"','') END, 
  CASE WHEN LENGTH(`m_short_description`) = 0 THEN "NONE" ELSE REPLACE(`m_short_description`,'"','') END, 
	round(`m_price`,2),
	NULL,
	NULL,
	NULL,
	"0",
	`m_weight`,
	`m_manufacturer`,	
	REPLACE(`m_meta_title`,'"',''),
	NULL,
  REPLACE(`m_meta_description`,'"',''),   
	concat("/",substr(`m_mbk_product_code`,1,1),"/",substr(`m_mbk_product_code`,2,1),"/", `m_mbk_product_code`,".jpg"),
	concat("/",substr(`m_mbk_product_code`,1,1),"/",substr(`m_mbk_product_code`,2,1),"/", `m_mbk_product_code`,".jpg"),
	concat("/",substr(`m_mbk_product_code`,1,1),"/",substr(`m_mbk_product_code`,2,1),"/", `m_mbk_product_code`,".jpg"),
	NULL,
	NULL,
	NULL,
	NULL,
	concat("/", `m_mbk_product_code`,".jpg"),
	"1",
	"2",
	NULL,
	NULL,
	NULL,
	"4",
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	"Block after Info Column",
	"0",
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	"1",
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
  CASE WHEN LENGTH(`m_mbk_features_area`) = 0 THEN "NONE" ELSE REPLACE(`m_mbk_features_area`,'"','') END,
	NULL,
	round(`m_mbk_retail_price`,2),
	NULL,
	`m_sku`,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	round(`m_special_price`,2),
	`m_qty`,
	"0",
	"0",
	"1",
	"0",
	"0",
	"1",
  "0",
	`m_max_sale_qty`,
	"0",
	"1",
	`m_notify_stock_qty`,
	"1",
	"0",
	"1",
	"1",
	"0",
	"1",
	"0",
	NULL,	
	NULL,		
	NULL,	
	NULL,	
	NULL,		
	NULL,
	NULL,	
	NULL,
	NULL,	
	CASE WHEN (`m__tier_price_price` IS NULL) THEN NULL ELSE "all" END,	
	CASE WHEN (`m__tier_price_price` IS NULL) THEN NULL ELSE "4" END,	
	CASE WHEN (`m__tier_price_price` IS NULL) THEN NULL ELSE "1" END,	
  CASE WHEN (`m__tier_price_price` IS NULL) THEN NULL ELSE round(`m__tier_price_price`,2) END,
	`mbk_import_update`,
	`mbk_import_new`,
	0,
	now(),
	now()
	from `vm_merged`.`vm_merged_products` where (`vm_merged_products`.`mbk_import_update`=1 or `vm_merged_products`.`mbk_import_new`=1) AND `m_category_ids` IS NOT NULL GROUP BY `m_mbk_product_code`);
	update `vm_merged`.`vm_merged_products` set `mbk_import_update`=0, `mbk_import_new`=0;
