insert into `vm_merged_products` (select 
round(productprice,2)   as `v_productprice`,
round(listprice,2)      as `v_listprice`,
categoryids             as `v_categoryid`,
categoryids             as `v_categoryids`,
productcode             as `v_productcode`,
productname             as `v_productname`,
round(saleprice,2)      as `v_salesprice`,
productweight           as `v_productweight`,
productmanufacturer     as `v_productmanufacturer`,
taxableproduct          as `v_taxableproduct`,
productdescription      as `v_productdescription`,
productdescriptionshort as `v_productdescriptionshort`,
productfeatures         as `v_productfeatures`,
stockstatus             as `v_stockstatus`,
metatag_title           as `v_metatag_title`,
metatag_description     as `v_metatag_description`,
hideproduct             as `v_hideproduct`,
stocklowqtyalarm        as `v_stocklowqtyalarm`,
maxqty                  as `v_maxqty`,
howtogetsaleprice       as `v_howtogetsaleprice`,
round(discountedprice_level1,2)  as `v_discountedprice_level1`,
round(discountedprice_level3,2)  as `v_discountedprice_level3`,
yahoo_category          as `v_yahoo_category`,
displaybegindate        as `v_displaybegindate`,
round(productprice,2)   as `m_price`,
round(listprice ,2)     as `m_mbk_retail_price`,
categoryids             as `m_category_ids`,
productcode             as `m_sku`,
productcode             as `m_mbk_product_code`,
productname             as `m_name`,
round(saleprice,2)      as `m_special_price`,
productweight           as `m_weight`,
productmanufacturer     as `m_manufacturer`,
taxableproduct          as `m_tax_class_id`,
productdescription      as `m_description`,
productdescriptionshort as `m_short_description`,
productfeatures         as `m_mbk_features_area`,
stockstatus             as `m_qty`,
metatag_title           as `m_meta_title`,
metatag_description     as `m_meta_description`,
IF(hideproduct='Y',"1","0")  `m_status`,
stocklowqtyalarm        as `m_notify_stock_qty`,
maxqty                  as `m_max_sale_qty`,
round(discountedprice_level3,2)  as `m__tier_price_price`,
IF(howtogetsaleprice='addtocart',saleprice,NULL) as `m_mbk_map_price`,
0,
0,
0,
now(),
now()
from Products_Joined );


update `mbk_site_export_#{Time.now.strftime("%Y%m%d")}`.`Products_Joined` set 
`productprice` = #{},
`listprice` = #{},
`categoryids` = #{},
`productcode` = #{},
`productname` = #{},
`salesprice` = #{},
`productweight` = #{},
`productmanufacturer` = #{},
`taxableproduct` = #{},
`productdescription` = #{},
`productdescriptionshort` = #{},
`productfeatures` = #{},
`stockstatus` = #{},
`metatag_title` = #{},
`metatag_description` = #{},
`hideproduct` = #{},
`stocklowqtyalarm` = #{},
`maxqty` = #{},
`howtogetsaleprice` = #{},
`discountedprice_level1` = #{},
`discountedprice_level3` = #{},
`yahoo_category` = #{},
`displaybegindate`

insert into `mbk_site_export_#{Time.now.strftime("%Y%m%d")}`.`Products_Joined` (
`productprice`,
`listprice`,
`categoryids`,
`productcode`,
`productname`,
`salesprice`,
`productweight`,
`productmanufacturer`,
`taxableproduct`,
`productdescription`,
`productdescriptionshort`,
`productfeatures`,
`stockstatus`,
`metatag_title`,
`metatag_description`,
`hideproduct`,
`stocklowqtyalarm`,
`maxqty`,
`howtogetsaleprice`,
`discountedprice_level1`,
`discountedprice_level3`,
`yahoo_category`,
`displaybegindate`) values ()